# Generated by Django 4.2.7 on 2023-11-25 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eaters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
    ]
