# Generated by Django 4.2.7 on 2023-11-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaters', '0002_remove_menu_image_remove_owner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='owner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
