# Generated by Django 4.2.7 on 2023-11-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaters', '0003_menu_image_owner_image_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
